version: '3.8'

services:
  # Main vulnerability analyzer service
  vuln-analyzer:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: vuln-analyzer
    restart: unless-stopped
    environment:
      - CVE_DATA_PATH=/app/data/cvelistV5/cves
      - DATABASE_PATH=/app/data/databases/cve_database.db
      - KEV_FILE_PATH=/app/data/known_exploited_vulnerabilities.json
      - DOWNLOAD_DIR=/app/data/downloads
      - LOG_LEVEL=INFO
    volumes:
      - vuln_data:/app/data
      - vuln_config:/app/config
      - vuln_logs:/app/logs
    networks:
      - vuln_network
    command: ["--help"]

  # Development environment
  vuln-analyzer-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    container_name: vuln-analyzer-dev
    environment:
      - CVE_DATA_PATH=/app/data/cvelistV5/cves
      - DATABASE_PATH=/app/data/databases/cve_database.db
      - KEV_FILE_PATH=/app/data/known_exploited_vulnerabilities.json
      - DOWNLOAD_DIR=/app/data/downloads
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
    volumes:
      - .:/app:rw  # Mount source code for development
      - vuln_data_dev:/app/data
      - vuln_config_dev:/app/config
      - vuln_logs_dev:/app/logs
    networks:
      - vuln_network
    profiles:
      - dev
    command: ["shell"]

  # Database builder service
  database-builder:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: vuln-database-builder
    environment:
      - CVE_DATA_PATH=/app/data/cvelistV5/cves
      - DATABASE_PATH=/app/data/databases/cve_database.db
      - KEV_FILE_PATH=/app/data/known_exploited_vulnerabilities.json
      - LOG_LEVEL=INFO
    volumes:
      - vuln_data:/app/data
      - vuln_logs:/app/logs
    networks:
      - vuln_network
    profiles:
      - setup
    command: ["create-database"]

  # CVE downloader service
  cve-downloader:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: vuln-cve-downloader
    environment:
      - CVE_DATA_PATH=/app/data/cvelistV5/cves
      - DOWNLOAD_DIR=/app/data/downloads
      - KEV_FILE_PATH=/app/data/known_exploited_vulnerabilities.json
      - NVD_API_KEY=${NVD_API_KEY:-}  # Set this in .env file
      - LOG_LEVEL=INFO
    volumes:
      - vuln_data:/app/data
      - vuln_logs:/app/logs
    networks:
      - vuln_network
    profiles:
      - download
    command: ["download-cves", "--recent-days", "30", "--max-retries", "5"]

  # Database query service
  query-service:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: vuln-query-service
    environment:
      - DATABASE_PATH=/app/data/databases/cve_database.db
      - LOG_LEVEL=INFO
    volumes:
      - vuln_data:/app/data:ro  # Read-only access
    networks:
      - vuln_network
    profiles:
      - query
    command: ["query-database", "stats"]

  # Future: Web API service (placeholder)
  # web-api:
  #   build:
  #     context: .
  #     target: production
  #     dockerfile: Dockerfile
  #   container_name: vuln-web-api
  #   environment:
  #     - DATABASE_PATH=/app/data/databases/cve_database.db
  #     - LOG_LEVEL=INFO
  #     - FLASK_ENV=production
  #   volumes:
  #     - vuln_data:/app/data:ro
  #   networks:
  #     - vuln_network
  #   ports:
  #     - "8000:8000"
  #   profiles:
  #     - web
  #   command: ["web-server"]

volumes:
  # Production volumes
  vuln_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  vuln_config:
    driver: local
  vuln_logs:
    driver: local
  
  # Development volumes
  vuln_data_dev:
    driver: local
  vuln_config_dev:
    driver: local
  vuln_logs_dev:
    driver: local

networks:
  vuln_network:
    driver: bridge

# Configuration for different usage scenarios
x-common-env: &common-env
  CVE_DATA_PATH: /app/data/cvelistV5/cves
  DATABASE_PATH: /app/data/databases/cve_database.db
  KEV_FILE_PATH: /app/data/known_exploited_vulnerabilities.json
  DOWNLOAD_DIR: /app/data/downloads
  LOG_LEVEL: INFO 